# Generated by Django 5.2 on 2025-04-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_alter_coffee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.CharField(max_length=20)),
                ('coffee_variety', models.CharField(max_length=100)),
                ('fertilizer_used', models.CharField(max_length=100)),
                ('hectares_of_land', models.FloatField()),
                ('previous_yield', models.FloatField()),
                ('presence_of_buds', models.CharField(max_length=10)),
                ('weather_condition', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
