# Generated by Django 5.2 on 2025-04-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_farminfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farminfo',
            name='coffee_variety',
            field=models.CharField(choices=[('Ruiru 11', 'Ruiru 11'), ('Batian', 'Batian'), ('SL24', 'SL24'), ('SL38', 'SL38')], max_length=100),
        ),
    ]
