# Generated by Django 5.2 on 2025-04-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_alter_farminfo_coffee_variety'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farminfo',
            name='fertilizer_used',
        ),
        migrations.AddField(
            model_name='farminfo',
            name='fertilizer_amount',
            field=models.FloatField(default=0),
        ),
    ]
